#!/bin/bash
# Check how many arguments were passed.
if [[ $# -gt 2 ]]; then
	echo "Usage: scribe <filename> <extension>."
	exit
fi

# Define the target variable as name/name.extension. If no extension exists, use name/name.
if [[ $# -eq 2 ]]
	then
		target="$1/$1.$2"
	else
		target="$1/$1"
fi

# First, check if the file exists.
if ! [[ -f "$target" ]]; then
	mkdir $1
fi

vim $target
